[package]
name = "matrix_operations"
version = "0.1.0"
authors = ["arnaud111"]
edition = "2021"
description = "A library to perform matrix operations"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
